basepath = "."

locales = [
  "en-US",
  "ja",
  "ko",
  "zh-CN",
  "zh-TW",
]

# Expose the following branches to localization
# Changes to this list should be announced to the l10n team ahead of time.
branches = [
    "main",
]

[env]

[[paths]]
  reference = "locales/en-US/ios.xliff"
  l10n = "locales/en-US/{locale}/ios.xliff"
